[package]
name = "async_py"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"]  }
thiserror = "2.0"
serde_json = "1.0.145"
dunce = "1.0.5"

[dev-dependencies]
tempfile = "3"

# The `full` feature for tokio is needed for the tests
[dev-dependencies.tokio]
version = "1"
features = ["full"]